name: PR Deployments

on: pull_request

jobs:
  UnitTests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps
        run: npm install

      - name: Run unit tests
        run: npm run test

  E2ETests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps
        run: npm install

      - name: Run e2e tests
        run: npm run e2e:run

  Build:
    runs-on: ubuntu-22.04
    needs: [UnitTests, E2ETests]
    permissions:
      contents: write
      id-token: write
    environment:
      name: staging
      url: ${{env.PUBLIC_URL}}/
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps
        run: npm install

      - name: Init deployment URL
        id: deployment_url
        run: echo "PUBLIC_URL=${{vars.PUBLIC_URL}}/${{github.head_ref}}" >> $GITHUB_ENV

      - name: Build application
        run: npm run build

      - uses: JamesIves/github-pages-deploy-action@v4.4.1
        id: deployment
        with:
          folder: ./build
          target-folder: ${{github.head_ref}}
          clean: false
